packages:
  - applications/**

onlyBuiltDependencies:
  - '@heroui/shared-utils'
  - '@journeyapps/sqlcipher'
  - '@tailwindcss/oxide'
  - classic-level
  - esbuild
  - ngrok
  - onnxruntime-node
  - protobufjs
  - sharp
  - sqlite3
  - better-sqlite3
